# Generated by Django 5.0.7 on 2024-09-08 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('subjects', '0002_alter_chapter_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default=uuid.UUID('24f0d529-1e65-4038-84e4-9600114d45ca'), on_delete=django.db.models.deletion.CASCADE, related_name='subjects', related_query_name='subject', to='curriculum.grade'),
        ),
    ]
