# Generated by Django 5.0.7 on 2024-08-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_cover_pic_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.SmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('cover', models.ImageField(default='default.jpg', upload_to='chapter_covers')),
                ('caption', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('intro', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('lecture_video', models.FileField(blank=True, null=True, upload_to='lecture_videos')),
                ('section_video', models.FileField(blank=True, null=True, upload_to='sections_videos')),
                ('starting_time', models.DateTimeField(blank=True, null=True)),
                ('ending_time', models.DateTimeField(blank=True, null=True)),
                ('cover', models.ImageField(default='default.jpg', upload_to='lesson_covers')),
                ('notes', models.TextField(blank=True, null=True)),
                ('requires', models.JSONField(blank=True, null=True)),
                ('required_by', models.JSONField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter')),
            ],
        ),
    ]
