# Generated by Django 5.0.7 on 2024-08-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_chapter_title_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
