# Generated by Django 5.0.7 on 2024-08-11 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_lesson_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subjects.unit'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subjects.chapter'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='subjects.subject'),
        ),
    ]
