# Generated by Django 5.0.7 on 2024-08-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_chapter_unit_alter_lesson_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='cover_pic',
            new_name='cover',
        ),
    ]
