# Generated by Django 5.0.7 on 2024-08-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_rename_cover_pic_subject_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
    ]
