# Generated by Django 5.0.7 on 2024-08-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_semester_ending_date_and_more'),
        ('subjects', '0008_remove_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.grade'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.semester'),
        ),
    ]
