# Generated by Django 5.0.7 on 2024-08-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_lesson_grade_lesson_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
    ]
