# Generated by Django 5.0.7 on 2024-08-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(max_length=256),
        ),
    ]
