# Generated by Django 5.0.7 on 2024-08-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answer_question'),
        ('subjects', '0009_lesson_grade_lesson_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.lesson'),
        ),
    ]
