# Generated by Django 5.0.7 on 2044-08-09 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2044, 8, 9, 12, 37, 37, 752024))),
                ('school', models.CharField(choices=[('nat_ar', 'Arabic national curriculum'), ('nat_en', 'English national curriculum')], max_length=6)),
                ('school_year', models.CharField(choices=[('1-sec', 'First secondary school'), ('2-sec', 'Second secondary school'), ('3-sec', 'Third secondary school')], max_length=5)),
                ('division', models.CharField(choices=[('lit', 'literary'), ('sci', 'science')], max_length=3)),
                ('second_language', models.CharField(choices=[('fr', 'French'), ('ge', 'German')], max_length=2)),
                ('term', models.CharField(choices=[('0', 'No term (over the year)'), ('1', 'first'), ('2', 'second')], max_length=1)),
                ('starting_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
