# Generated by Django 5.0.7 on 2044-08-09 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2044, 8, 9, 12, 38, 50, 764273, tzinfo=datetime.timezone.utc)),
        ),
    ]
