# Generated by Django 5.0.7 on 2044-08-09 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_curriculum_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
