# Generated by Django 5.0.7 on 2044-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_curriculum_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
