# Generated by Django 5.0.7 on 2024-08-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_curriculum_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='division',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='school',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='second_language',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='starting_date',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='term',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='name',
            field=models.CharField(default='arabic', max_length=32),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum')),
            ],
        ),
    ]
