# Generated by Django 5.0.7 on 2024-08-13 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_remove_curriculum_created_at_and_more'),
        ('subjects', '0008_remove_subject_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('first', 'first term'), ('second', 'second term'), (None, 'No term')], max_length=16)),
                ('starting_date', models.DateField(default=datetime.date(2024, 9, 1))),
                ('ending_date', models.DateField(default=datetime.date(2025, 12, 31))),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.grade')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subjects.lesson')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.semester')),
            ],
        ),
    ]
