# Generated by Django 5.0.7 on 2024-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_semester_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='ending_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='starting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='title',
            field=models.CharField(choices=[('1', 'first term'), ('2', 'second term'), (None, 'No term')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
