# Generated by Django 5.0.7 on 2024-08-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_semester_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='title',
            field=models.CharField(choices=[('1', 'first term'), ('2', 'second term'), ('0', 'No term')], max_length=1),
        ),
    ]
