# Generated by Django 5.0.7 on 2024-09-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tagged_lessons',
            field=models.ManyToManyField(blank=True, related_name='tagging_students', to='subjects.lesson'),
        ),
    ]
