# Generated by Django 5.0.7 on 2024-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_rename_name_subject_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tagged_lessons',
            field=models.ManyToManyField(related_name='tagged_students', to='subjects.lesson'),
        ),
    ]
