# Generated by Django 5.0.7 on 2024-08-17 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
    ]
