# Generated by Django 5.0.7 on 2024-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
