# Generated by Django 5.0.7 on 2024-08-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
