# Generated by Django 5.0.7 on 2024-10-10 23:44

import django.db.models.deletion
import resources.models.base
import resources.models.lesson
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grades", "0005_alter_semester_curriculum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name (case-insensitive).",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TextBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the resource to add in the card.",
                        null=True,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=resources.models.base.cover_path,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textbooks",
                        related_query_name="textbook",
                        to="resources.subject",
                    ),
                ),
            ],
            options={
                "db_table": "textbooks",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the resource to add in the card.",
                        null=True,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=resources.models.base.cover_path,
                    ),
                ),
                (
                    "syllabus_order",
                    models.IntegerField(
                        default=1,
                        help_text="The order of the resource in the syllabus.",
                    ),
                ),
                (
                    "text_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        related_query_name="unit",
                        to="resources.textbook",
                    ),
                ),
            ],
            options={
                "db_table": "units",
                "ordering": ["text_book", "syllabus_order"],
                "unique_together": {("text_book", "syllabus_order")},
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the resource to add in the card.",
                        null=True,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=resources.models.base.cover_path,
                    ),
                ),
                (
                    "syllabus_order",
                    models.IntegerField(
                        default=1,
                        help_text="The order of the resource in the syllabus.",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        related_query_name="chapter",
                        to="resources.unit",
                    ),
                ),
            ],
            options={
                "db_table": "chapters",
                "ordering": ["unit", "syllabus_order"],
                "unique_together": {("unit", "syllabus_order")},
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the resource to add in the card.",
                        null=True,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=resources.models.base.cover_path,
                    ),
                ),
                (
                    "syllabus_order",
                    models.IntegerField(
                        default=1,
                        help_text="The order of the resource in the syllabus.",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="A brief introduction of the lesson in a way to draw attention.",
                        null=True,
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True,
                        help_text="What a student should gain after this lesson.",
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="The main content of the lesson.",
                        null=True,
                    ),
                ),
                (
                    "lecture_vid",
                    models.FileField(
                        blank=True,
                        help_text="A video of the lecture for the lesson.",
                        null=True,
                        upload_to=resources.models.lesson.lesson_lecture_vid_path,
                    ),
                ),
                (
                    "section_vid",
                    models.FileField(
                        blank=True,
                        help_text="A video for solving problems and answering questions of the lesson.",
                        null=True,
                        upload_to=resources.models.lesson.lesson_section_vid_path,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        related_query_name="lesson",
                        to="resources.chapter",
                    ),
                ),
                (
                    "requires",
                    models.ManyToManyField(
                        blank=True,
                        help_text="This field holds the lessons that should be completed before this lesson.",
                        related_name="required_by",
                        to="resources.lesson",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        help_text="The semester this lesson belongs to in syllabus.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grades.semester",
                    ),
                ),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["chapter", "syllabus_order"],
                "unique_together": {("chapter", "syllabus_order")},
            },
        ),
    ]
