# Generated by Django 5.0.7 on 2024-10-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["syllabus_order"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["syllabus_order"]},
        ),
    ]
