# Generated by Django 5.0.7 on 2024-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="requires",
            field=models.ManyToManyField(
                blank=True, related_name="required_by", to="resources.lesson"
            ),
        ),
    ]
