# Generated by Django 5.0.7 on 2024-10-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_alter_semester_curriculum"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unit",
            old_name="textBook",
            new_name="text_book",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="syllabus_order",
            field=models.IntegerField(
                default=1, help_text="The order of the resource in the syllabus."
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="syllabus_order",
            field=models.IntegerField(
                default=1, help_text="The order of the resource in the syllabus."
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="syllabus_order",
            field=models.IntegerField(
                default=1, help_text="The order of the resource in the syllabus."
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("unit", "syllabus_order"), name="unique_unit_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("chapter", "syllabus_order"), name="unique_chapter_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("text_book", "syllabus_order"), name="unique_text_book_order"
            ),
        ),
    ]
