# Generated by Django 5.0.7 on 2024-10-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_rename_textbook_unit_text_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                related_query_name="chapter",
                to="resources.unit",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                related_query_name="lesson",
                to="resources.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="textbook",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="textbooks",
                related_query_name="textbook",
                to="resources.subject",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="text_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                related_query_name="unit",
                to="resources.textbook",
            ),
        ),
    ]
