# Generated by Django 5.0.7 on 2024-10-09 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_chapter_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["unit", "syllabus_order"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["chapter", "syllabus_order"]},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["text_book", "syllabus_order"]},
        ),
    ]
