# Generated by Django 5.0.7 on 2024-10-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_alter_chapter_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chapter",
            name="unique_unit_order",
        ),
        migrations.RemoveConstraint(
            model_name="lesson",
            name="unique_chapter_order",
        ),
        migrations.RemoveConstraint(
            model_name="unit",
            name="unique_text_book_order",
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("unit", "syllabus_order")},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("chapter", "syllabus_order")},
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("text_book", "syllabus_order")},
        ),
    ]
