# Generated by Django 5.0.7 on 2024-10-05 18:28

import django.db.models.deletion
import resources.models.lesson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_alter_semester_curriculum"),
        ("resources", "0003_alter_lesson_requires"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="order_index",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="order_index",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="order_index",
        ),
        migrations.AddField(
            model_name="chapter",
            name="syllabus_order",
            field=models.IntegerField(
                default=1,
                help_text="The order of the resource in the syllabus.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="syllabus_order",
            field=models.IntegerField(
                default=1,
                help_text="The order of the resource in the syllabus.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="textbook",
            name="syllabus_order",
            field=models.IntegerField(
                default=1,
                help_text="The order of the resource in the syllabus.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="syllabus_order",
            field=models.IntegerField(
                default=1,
                help_text="The order of the resource in the syllabus.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the resource to add in the card.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the resource to add in the card.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="details",
            field=models.TextField(
                blank=True, help_text="The main content of the lesson.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="goals",
            field=models.TextField(
                blank=True,
                help_text="What a student should gain after this lesson.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="A brief introduction of the lesson in a way to draw attention.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lecture_vid",
            field=models.FileField(
                blank=True,
                help_text="A video of the lecture for the lesson.",
                null=True,
                upload_to=resources.models.lesson.lesson_lecture_vid_path,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="section_vid",
            field=models.FileField(
                blank=True,
                help_text="A video for solving problems and answering questions of the lesson.",
                null=True,
                upload_to=resources.models.lesson.lesson_section_vid_path,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                help_text="The semester this lesson belongs to in syllabus.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grades.semester",
            ),
        ),
        migrations.AlterField(
            model_name="textbook",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the resource to add in the card.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the resource to add in the card.",
                null=True,
            ),
        ),
    ]
