# Generated by Django 5.0.7 on 2024-09-30 20:43

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("INTERNATIONAL", "International"),
                        ],
                        default="NATIONAL",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "curriculums",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FIRST_TERM", "First term"),
                            ("SECOND_TERM", "Second term"),
                            ("No_TERM", "No term - Full year"),
                            ("SUMMER_COURSE", "Summer course"),
                        ],
                        default="FIRST_TERM",
                        max_length=255,
                    ),
                ),
                ("starts_at", models.DateField(default=datetime.date(2024, 9, 1))),
                ("ends_at", models.DateField(default=datetime.date(2024, 12, 31))),
            ],
            options={
                "db_table": "semesters",
            },
        ),
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "main_language",
                    models.CharField(
                        choices=[("ENGLISH", "English"), ("ARABIC", "Arabic")],
                        default="ENGLISH",
                        max_length=32,
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        related_query_name="path",
                        to="grades.curriculum",
                    ),
                ),
            ],
            options={
                "db_table": "paths",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("order_in_path", models.PositiveIntegerField()),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        related_query_name="stage",
                        to="grades.path",
                    ),
                ),
            ],
            options={
                "db_table": "stages",
                "ordering": ["order_in_path"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("order_in_stage", models.PositiveIntegerField()),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        related_query_name="grade",
                        to="grades.stage",
                    ),
                ),
            ],
            options={
                "db_table": "grades",
                "ordering": ["order_in_stage"],
            },
        ),
    ]
