# Generated by Django 5.0.7 on 2024-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
