# Generated by Django 5.0.7 on 2024-10-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_curriculum_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="curriculum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="grades.curriculum",
            ),
        ),
    ]
