# Generated by Django 5.0.7 on 2024-10-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_alter_semester_curriculum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                related_query_name="semester",
                to="grades.curriculum",
            ),
        ),
    ]
