# Generated by Django 5.0.7 on 2024-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="initial_max_students",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="max_students",
            field=models.PositiveIntegerField(
                default=models.PositiveIntegerField(default=10)
            ),
        ),
    ]
