# Generated by Django 5.0.7 on 2024-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teacher_initial_max_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="max_students",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
