# Generated by Django 5.0.7 on 2024-10-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_teacher_max_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="initial_max_students",
        ),
    ]
