# Generated by Django 5.0.7 on 2024-10-14 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("questions", "0002_initial"),
        ("resources", "0001_initial"),
        ("users", "0004_remove_teacher_initial_max_students"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="An optional title for the exam",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("duration", models.IntegerField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("Lesson", "Lesson"),
                            ("Chapter", "Chapter"),
                            ("Unit", "Unit"),
                            ("TextBook", "Textbook"),
                            ("Multiple", "Multiple"),
                        ],
                        default="Lesson",
                        max_length=10,
                    ),
                ),
                (
                    "scope_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The id of the scope object (Lesson, Chapter, Unit, or TextBook).",
                        null=True,
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="exams",
                        related_query_name="exam",
                        to="classes.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        related_query_name="exam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multi_scope",
                    models.ManyToManyField(blank=True, to="resources.lesson"),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        related_query_name="exam_question",
                        to="exams.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        related_query_name="exam_question",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                through="exams.ExamQuestions", to="questions.question"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.choice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "indexes": [
                    models.Index(
                        fields=["exam", "student"],
                        name="exams_answe_exam_id_ad2752_idx",
                    )
                ],
                "unique_together": {("exam", "student", "choice")},
            },
        ),
        migrations.AddIndex(
            model_name="examquestions",
            index=models.Index(fields=["exam"], name="exams_examq_exam_id_824fec_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="examquestions",
            unique_together={("exam", "question")},
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["scope_type", "scope_id"], name="exams_exam_scope_t_af0209_idx"
            ),
        ),
    ]
