# Generated by Django 5.0.7 on 2024-10-10 23:44

import questions.models.choice
import questions.models.questions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "figure",
                    models.ImageField(
                        blank=True,
                        help_text="Choice figure (diagram, graph, etc.)",
                        null=True,
                        upload_to=questions.models.choice.choice_figure_path,
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "choices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                            ("VERY HARD", "Very Hard"),
                        ],
                        default="EASY",
                        max_length=32,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        help_text="Detailed solution (soluation manual)",
                        null=True,
                    ),
                ),
                (
                    "figure",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="Question figure (diagram, graph, etc.)",
                        null=True,
                        upload_to=questions.models.questions.question_figure_path,
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["?"],
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description for this type of questions.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "types",
                "ordering": ["name"],
            },
        ),
    ]
