# Generated by Django 5.0.7 on 2024-10-10 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                related_query_name="question",
                to="resources.lesson",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                related_query_name="choice",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types",
                related_query_name="type",
                to="resources.subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                related_query_name="question",
                to="questions.type",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("body__isnull", False), ("figure__isnull", False), _connector="OR"
                ),
                name="body_figure_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question", "is_correct"),
                name="unique_correct_choice",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="type",
            unique_together={("name", "subject")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="questions_difficu_8150ad_idx"
            ),
        ),
    ]
