# Generated by Django 5.0.7 on 2024-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Enter a description for this type of questions.",
                null=True,
            ),
        ),
    ]
