# Generated by Django 5.0.7 on 2024-10-09 21:15

import questions.models.questions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_type_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="figure",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Question figure (diagram, graph, etc.)",
                null=True,
                upload_to=questions.models.questions.question_figure_path,
            ),
        ),
    ]
