# Generated by Django 5.0.7 on 2024-10-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_question_figure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Easy"),
                    ("MEDIUM", "Medium"),
                    ("HARD", "Hard"),
                    ("VERY HARD", "Very Hard"),
                ],
                default="EASY",
                max_length=32,
            ),
        ),
    ]
