# Generated by Django 5.0.7 on 2024-10-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_question_difficulty"),
        ("resources", "0003_alter_chapter_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="type",
            constraint=models.UniqueConstraint(
                fields=("subject", "name"), name="unique_subject_type"
            ),
        ),
    ]
