# Generated by Django 5.0.7 on 2024-10-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_type_unique_subject_type"),
        ("resources", "0003_alter_chapter_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="questions_difficu_8150ad_idx"
            ),
        ),
    ]
