# Generated by Django 5.0.7 on 2024-10-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_question_questions_difficu_8150ad_idx"),
        ("resources", "0004_remove_chapter_unique_unit_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="type",
            name="unique_subject_type",
        ),
        migrations.AlterUniqueTogether(
            name="type",
            unique_together={("name", "subject")},
        ),
    ]
