# Generated by Django 5.0.7 on 2024-10-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_remove_type_unique_subject_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                related_query_name="question",
                to="questions.type",
            ),
        ),
    ]
