# Generated by Django 5.0.7 on 2024-10-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_alter_question_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question", "is_correct"),
                name="unique_correct_choice",
            ),
        ),
    ]
